// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cardio_sessions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCardioSession = `-- name: CreateCardioSession :one
INSERT INTO cardio_sessions (workout_id, exercise_id, distance, time, notes, created_at, updated_at)
VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	NOW(),
	NOW()
)
RETURNING id, workout_id, exercise_id, distance, time, notes, created_at, updated_at
`

type CreateCardioSessionParams struct {
	WorkoutID  uuid.UUID
	ExerciseID uuid.UUID
	Distance   string
	Time       int64
	Notes      sql.NullString
}

func (q *Queries) CreateCardioSession(ctx context.Context, arg CreateCardioSessionParams) (CardioSession, error) {
	row := q.db.QueryRowContext(ctx, createCardioSession,
		arg.WorkoutID,
		arg.ExerciseID,
		arg.Distance,
		arg.Time,
		arg.Notes,
	)
	var i CardioSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.Distance,
		&i.Time,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
