// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: exercises.sql

package database

import (
	"context"
)

const createExercise = `-- name: CreateExercise :one
INSERT INTO exercises (id, name, exercise_type, notes)
VALUES (
	gen_random_uuid(),
	$1,
	$2,
	$3
)
RETURNING id, name, exercise_type, notes
`

type CreateExerciseParams struct {
	Name         string
	ExerciseType string
	Notes        string
}

func (q *Queries) CreateExercise(ctx context.Context, arg CreateExerciseParams) (Exercise, error) {
	row := q.db.QueryRowContext(ctx, createExercise, arg.Name, arg.ExerciseType, arg.Notes)
	var i Exercise
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ExerciseType,
		&i.Notes,
	)
	return i, err
}
