// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CardioSession struct {
	ID         uuid.UUID
	WorkoutID  uuid.UUID
	ExerciseID uuid.UUID
	Distance   string
	Time       int64
	Notes      sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type Exercise struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	Name         string
	ExerciseType string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type StrengthTrainingSession struct {
	ID         uuid.UUID
	WorkoutID  uuid.UUID
	ExerciseID uuid.UUID
	Notes      sql.NullString
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type StrengthTrainingSet struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	SessionID uuid.UUID
	SetNumber int32
	Reps      int32
	Weight    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Workout struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	WorkoutDate time.Time
	WorkoutType string
	Notes       sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
