// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type CardioSession struct {
	ID         uuid.UUID
	WorkoutID  uuid.NullUUID
	ExerciseID uuid.NullUUID
	Distance   sql.NullString
	Time       sql.NullInt64
	Notes      sql.NullString
}

type Exercise struct {
	ID           uuid.UUID
	Name         string
	ExerciseType sql.NullString
	Notes        sql.NullString
}

type StrengthTrainingSession struct {
	ID         uuid.UUID
	WorkoutID  uuid.NullUUID
	ExerciseID uuid.NullUUID
	Notes      sql.NullString
}

type StrengthTrainingSet struct {
	ID        uuid.UUID
	SessionID uuid.NullUUID
	SetNumber int32
	Reps      int32
	Weight    string
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
}

type Workout struct {
	ID          uuid.UUID
	UserID      uuid.NullUUID
	WorkoutDate sql.NullTime
	WorkoutType sql.NullString
	Notes       sql.NullString
}
