// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: strength_training_sessions.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createStrengthTrainingSession = `-- name: CreateStrengthTrainingSession :one
INSERT INTO strength_training_sessions (workout_id, exercise_id, notes, created_at, updated_at)
VALUES (
	$1,
	$2,
	$3,
	NOW(),
	NOW()
)
RETURNING id, workout_id, exercise_id, notes, created_at, updated_at
`

type CreateStrengthTrainingSessionParams struct {
	WorkoutID  uuid.UUID
	ExerciseID uuid.UUID
	Notes      sql.NullString
}

func (q *Queries) CreateStrengthTrainingSession(ctx context.Context, arg CreateStrengthTrainingSessionParams) (StrengthTrainingSession, error) {
	row := q.db.QueryRowContext(ctx, createStrengthTrainingSession, arg.WorkoutID, arg.ExerciseID, arg.Notes)
	var i StrengthTrainingSession
	err := row.Scan(
		&i.ID,
		&i.WorkoutID,
		&i.ExerciseID,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
