// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: strength_training_sets.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createStrengthTrainingSet = `-- name: CreateStrengthTrainingSet :exec
INSERT INTO strength_training_sets (session_id, set_number, reps, weight, created_at, updated_at)
VALUES (
	$1,
	$2,
	$3,
	$4,
	NOW(),
	NOW()
)
`

type CreateStrengthTrainingSetParams struct {
	SessionID uuid.UUID
	SetNumber int32
	Reps      int32
	Weight    string
}

func (q *Queries) CreateStrengthTrainingSet(ctx context.Context, arg CreateStrengthTrainingSetParams) error {
	_, err := q.db.ExecContext(ctx, createStrengthTrainingSet,
		arg.SessionID,
		arg.SetNumber,
		arg.Reps,
		arg.Weight,
	)
	return err
}
